### ISSUE TITLE
Loading "websocketbridge.js" failed.

### ISSUE THREAD

**Issue by satyasashi** [arocks/channels-example#1]
Hi I was following the tutorial step by step. When I added the JavaScript code the **home.html**, and refreshed the page, I see there is a Warning and a Error:

_Warning: Loading failed for the <script> with source “http://localhost:8000/static/channels/js/websocketbridge.js”_

_ReferenceError: channels is not defined_

Can you tell me what to do to resolve this issue?

**Comment by arocks** [comment]
Channels upstream stopped bundling the websocketbridge.js file. You can find it now in this repository under `/js/websocketbridge.js`.
